### ISSUE TITLE
Nothing happen after 

### ISSUE THREAD

**Issue by madan3** [consik/yii2-websocket#1]
![capture](https://cloud.githubusercontent.com/assets/15029754/22505146/2b044356-e87a-11e6-9072-4c01ceb51f58.PNG)
Neither I can set user name nor I can send message. I try to console 

  chat.send( JSON.stringify({'action' : 'chat', 'message' : $('#message').val()}) );
  chat.send( JSON.stringify({'action' : 'setName', 'name' : $('#username').val()}) )

both are undefined. And I more I have view page chart in place of chat Why?

**Comment by consik** [comment]
In example variable "chat" initialized in $(function() { ..here..} ) and you can't call its methods outside from console.
