### ISSUE TITLE
ucfirst seems to not do its part

### ISSUE THREAD

**Issue by adzadzadz** [consik/yii2-websocket#10]
This is so weird, I've verified $command to be a String and also tested ucfirst with a static string and it works. But when ucfirst is used with $command ( ucfirst($command) ), it isn't returning as it should. Please refer to the screenshot. I will try and fix this in my end. 
<img width="1366" alt="screen shot 2018-05-30 at 3 33 38 am" src="https://user-images.githubusercontent.com/4595687/40681234-27d0f522-63bb-11e8-9635-1e6b9b20706d.png">

**Comment by adzadzadz** [comment]
fixed the issue by removing the double quote since it's a json string
ucfirst(trim($command, '"'))

**Comment by adzadzadz** [comment]
kindly update the

**Comment by adzadzadz** [comment]
Proposed fix https://github.com/consik/yii2-websocket/pull/11

**Comment by Consigliere-kz** [comment]
show me your getCommand method? 
You should normalize request to command name by overriding getCommand, not in onMessage method.

**Comment by adzadzadz** [comment]
````
    protected function getCommand(ConnectionInterface $from, $msg)
    {
        return json_decode($msg)->action;
    }
````

Yeah I agree. I was thinking of shortening the process where all the $msgs are commands which isn't usually the case. 

Anyway, I noticed that the connection closes for the frontend wherever I try to run an activerecord query such as User::findOne() but the connection in the server side is still running. Any insight with this?
