### ISSUE TITLE
How to closed socket through console after i start it?

### ISSUE THREAD

**Issue by shizzic** [consik/yii2-websocket#20]
I mean, i want to do it with my own hands, without ctrl + c. Socket connection for all connected user stop with keyboard, but trigger EVENT_WEBSOCKET_CLOSE doesn't work.

**Comment by temirfe** [comment]
you can type ctrl+c with your own hands )) I have a similar question: how to start it in background? If I close terminal the connection closes.

**Comment by vlad-ilinyh** [comment]
> how to start it in background?

https://github.com/consik/yii2-websocket#starting-yii2-console-application-as-daemon-using-nohup
