### ISSUE TITLE
WebSocket is already in CLOSING or CLOSED state.

### ISSUE THREAD

**Issue by abdulmanan7** [consik/yii2-websocket#3]
i implement the chat example you provided in document .
when i start the server ,put name in the username field and hit enter nothing happend but when again click the set username button this message appears in console.

WebSocket is already in CLOSING or CLOSED state.
(anonymous) @ index:740
dispatch @ jquery.js:4737
elemData.handle @ jquery.js:4549

i check my server and its still in running state .
please help me any idea 
regard

**Comment by consik** [comment]
Other examples works fine? Can't repeat your issue(
