### ISSUE TITLE
How do you send messages (invoke events) from PHP?

### ISSUE THREAD

**Issue by nssmart** [consik/yii2-websocket#6]
Examples show nicely how to send/receive messages from JS, and how to react (respond to messages received from JS in server).
Now the question is how to send messages from other php scripts?

**Comment by Consigliere-kz** [comment]
Hi!
There are two ways to send messages from another php script:
1) Use some buffer for collecting messages and read it from WebSocketServer. For example redis or DB table.
2) Look to some of php IPC solution. http://php.net/manual/ru/book.pthreads.php OR http://php.net/manual/en/book.sem.php. You can google the examples.

**Comment by nssmart** [comment]
Hi!
Thank you for a prompt reply.

Redis and IPC (inter-process communication) are some frech ideas to consider, thank you very much, I think I'll be looking deeper into them soon!

As for now, I got it working yesterday by using WebSocketClient from [another project](https://github.com/Textalk/websocket-php) that connects to the same socket and sends messages like:

    try {
        $connect = new WebSocketClient('ws://127.0.0.1', 8080);
        $connect->send(json_encode($data));
    }
    //...

Then my server goes like:

    /**
    * New message from php
    *
    * @param ConnectionInterface $client
    * @param string            $msg
    */
    public function commandMessage(ConnectionInterface $client, $msg)
    {
        if (!empty($this->clients))
        {
           $request = json_decode($msg, true);
           // ... make sure message comes from php by checking some values, prepare $data
           foreach ($this->clients as $client)
           {
              // .. only send to users in this "channel"
              if ($client->talkId == $talkId)
              {
                 $client->send(json_encode($data, true));
              }
           }
        }
    }

When my JS-clients subscribe, they send their chat ids (talkId) with "subscribe" command that I use to assign their talkIds that I check above (I'm on php7, hence can let myself use ??):

	/**
	 * Subscribe to messages
	 *
	 * @param ConnectionInterface $client
	 * @param string              $msg
	 */
	public function commandSubscribe(ConnectionInterface $client, $msg)
	{
		$request = @json_decode($msg, true);

		$client->talkId = $request['talk_id'] ?? null;
		$client->userId = $request['user_id'] ?? null;
	}

Just as one more way. I think will be useful to others with my problem.
p.s. Just as an idea, maybe you could add such a client to your project as well, so that users need not bringing one more dependency in projects?

Anyways, thanks again for the answer and for a great working piece of code.

**Comment by consik** [comment]
Hi. 
Yes, sure, you can use PHP websocket client to communicate with server as solution for your issue.
But I think IPC way is preferable. 

And I'm sorry, but I'm really too busy for adding some client into this repository (

Actually I wrote this code just for studying how to make websocket server on php and hadn't found convinient solution) Didn't expect that it will be useful for someone.

I hope I helped you with your issue :)

**Comment by hassanuos** [comment]
> https://github.com/consik/yii2-websocket/issues/6#issuecomment-359147296

It was really helpful for me. Thank you very much for saving my time, sir.

**Comment by nssmart** [comment]
> > [#6 (comment)](https://github.com/consik/yii2-websocket/issues/6#issuecomment-359147296)
> 
> It was really helpful for me. Thank you very much for saving my time, sir.

Very pleased to hear, sir! Thanks for sharing.
