### ISSUE TITLE
https / wss support

### ISSUE THREAD

**Issue by nssmart** [consik/yii2-websocket#7]
Hi again, and thanks for the server again!

Now as most servers run on https, browsers reject connections to ws:// by reasoning it with "Page was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint".
A bit of googling says it's due to an attempt at connecting to ws:// instead of wss:// (secure sockets).

How is it possible (if it is) to convert our server to wss with your extension?

Thank you in advance!

**Comment by consik** [comment]
Hi. You should use port 443 instead of 8080 in your server app. 
Or try to connect using this Url from your client:
wss://your.site:8080

**Comment by nssmart** [comment]
Thank you!
Got it working
