### ISSUE TITLE
Send Data

### ISSUE THREAD

**Issue by SereiaMaster** [consik/yii2-websocket#8]
How do I send data from a standard route from my controllers to the connected clients in the websocket? Can you help me?

**Comment by SereiaMaster** [comment]
Exemple: After anyone register one category in system... I wanna send this data to all clients in ws...

**Comment by consik** [comment]
Hi.
There are few ways to do it.
1) Use some buffer(DB, redis, etc...) for collecting events/messages and read it periodically in your WebSocket Server. 
2) Use IPC
3) Create WebSocket Client when you trigger event and send special message directly to the server.

Look at this issue https://github.com/consik/yii2-websocket/issues/6
